#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add to path
export PATH="$PATH:/usr/sbin"

# Use vim :)
export EDITOR=/usr/bin/vim
export VISUAL="$EDITOR"

# Include private configs
source ~/.zprezto/runcoms/private
