#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Use vim :)
export EDITOR=/usr/bin/vim

# Work proxy
export http_proxy=http://NOT.SHOWN.HERE:MYPORT
export https_proxy=$http_proxy
