#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add to path
export PATH="$PATH:/usr/sbin:/snap/bin:/home/jsmith/go/bin"

# Use vim :)
export EDITOR=/usr/bin/vim
export VISUAL="$EDITOR"

# Include private configs
source ~/.zprezto/runcoms/private

# Setup reverse search
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.zhistory
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward

# test if script is already started by this process, if not log all the things
PROCESS=`ps -ocommand= -p $PPID | awk '{print $1}'`
if [ "$PROCESS" != "script" ]; then
    script -f ~/scriptlog_`date +%Y%m%d_%H%M%S`.txt
fi
